### ISSUE TITLE
Dependabot

### ISSUE THREAD

**Issue by greysteil** [financial-times-sandbox/testing-123#6]
Hey @sjparkinson,

Saw you signed up for Dependabot (I get a summary email each morning) and thought I'd take a quick snoop around at whether you were getting on with it OK. Looks like you also decided to try Renovate - any opinions on the two? I'm always looking to improve Dependabot so any feedback is super helpful, and if there's any context I can provide as you choose between them then I'm more than happy to.

**Comment by sjparkinson** [comment]
Morning @greysteil, thanks for getting in touch.

We're looking at a few options at the moment, Greenkeeper, Renovate, and Dependabot.

Our tricky problem is how to best roll this out to ~200 repositories, without inundating our engineers.

I _really_ liked a lot of Dependabot actually, but our primary use-case initially is on managing the releases of our internal packages (scoped to `@financial-times`). So for us getting started in this brave new world of dependency management tools, Renovate looks to be a softer introduction for us.

Dependabot seems less configurable, and mainly for us doesn't support pattern matching on the package names for what should be tracked. Ideally we'll be working towards a point where this isn't actually an issue for us though.

We are always conscious of ensuring there are competitors available in a technology choice however, should the need arise to switch in the future.

**Comment by greysteil** [comment]
Ah, cool, pushing to 200 repos definitely needs some automation, and you don't want to be getting PRs you don't want x 200!

Renovate is super configurable, so they're a good option here. It's Rhys' big thing for it, and whilst it holds the tool back on some fronts it sounds like it could be exactly what you need here. Dependabot focuses more on ease of use and polish, which might not be what you need here, and whilst we're planning to add constraints on which packages it updates in the next couple of months it's not an option yet.

If I was in your shoes I'd probably give Greenkeeper a pass. They've got better recently, but their pace of development over the last few years hasn't been as quick as it should be, and they're still missing features that I think of as mandatory and their approach to lockfiles is still a bit flaky. They're probably also your most expensive option.

One other option, if you haven't considered it already, is to use a script to do this, since then you've got complete control and don't have to give a third party access. You've got a couple of options for that:
- The renovate app (well, most of it) is open source [here](https://github.com/renovatebot/renovate) and you could run it locally. That's probably not what you want as it's a whole app, rather than a script
- The core logic to Dependabot is open source [here](https://github.com/dependabot/dependabot-core) and is a library that you can include in a Ruby script. There's an example script [here](https://github.com/dependabot/dependabot-script) which could be customised to only update specific dependencies pretty easily

The downside to the script approach is obviously maintenance, but maybe worth considering. The upside is that it's (obviously) free and you have more control.

Best of luck with whatever approach you choose.

**Comment by greysteil** [comment]
(Also, if you go down the script route and are in London, ping me and I'd more than happily set it up with you over coffee. Always useful for me to meet users.)

**Comment by sjparkinson** [comment]
Thank you, honestly really helpful to get this sort of insight.

We're likely going to avoid the script route as much as possible and lean on the existing solutions. Part of our project is to reduce the magic that surrounds managing and deploying all of our repositories. We also get better documentation that way too 😂.

We have no meeting Wednesdays, and are encouraged to network, so I'd be more than happy to grab a coffee. We're based in London too. It might make sense to do once we've made some progress rolling this out, I'll set a reminder.

**Comment by greysteil** [comment]
Sounds great! I'm in San Francisco next week (it's GitHub Universe, which is a big event when you're a GitHub app but probably not on anyone else's radar), but shall we chat the following week?

I also used to be deputy CEO at GoCardless, which I know you folks are still using, so would be curious to hear how that's been, too (just out of curiosity!).

**Comment by sjparkinson** [comment]
That sounds good, Wednesday 24th, totally free. And I'll try and find out about our GoCardless setup, I'm a little disconnected from that, but it'd be good to be aware of myself.

My email is samuel.parkinson@ft.com, feel free to shoot me an invite for somewhere convenient for you.

**Comment by greysteil** [comment]
Awesome - have sent you an invite for coffee at Shoreditch Grind. I'm up in Dalston, so if you happen to be based up here too let's change the location, but otherwise see you there in a couple of weeks!
